FROM ubuntu:16.04

MAINTAINER Your Name "boezmen@uni-potsdam.de"

RUN apt-get update -y && \
    apt-get install -y software-properties-common && \
    add-apt-repository -y ppa:deadsnakes/ppa && \
    apt update -y && \
    apt-get install -y python3.7 python3-pip

# We copy just the requirements.txt first to leverage Docker cache
COPY ./requirements.txt /app/requirements.txt

WORKDIR /app

RUN python3.7 -m pip install -r requirements.txt

COPY . /app

ENV FLASK_APP=flaskr
ENV LC_ALL=C.UTF-8
ENV LANG=C.UTF-8